platform :ios, '7.0'
pod 'AFNetworking', '~> 2.5.4'
pod 'MD5Digest',    '~> 1.0.1'
pod 'jastor', '~> 0.2.1'
pod 'RETableViewManager', '~> 1.6'
pod 'ASIHTTPRequest', '~> 1.8.2'
pod 'SDWebImage', '~> 3.7.3'
pod 'YYKit', '~> 0.9.6'
pod 'Toast', '~> 3.0'
pod 'SDCycleScrollView','~> 1.3'
pod 'JTCalendar', '~> 2.1.4'
#pod 'YmsCoreBluetooth', '~> 1.10.0'
pod 'BabyBluetooth', '~> 0.5.0'
pod 'SVProgressHUD', '~> 2.0-beta'
pod 'Reveal-iOS-SDK', :configurations => ['Debug']
pod 'UMengAnalytics-NO-IDFA'
